### ISSUE TITLE
BioStructures fails to parse certain PDB files from SCOPe/ASTRAL archive

### ISSUE THREAD

**Issue by tanhevg** [BioJulia/BioStructures.jl#11]
## Expected Behavior
`BioStructures.jl` should be able to parse all files from  SCOPe/ASTRAL: http://scop.berkeley.edu/downloads/pdbstyle/pdbstyle-sel-gs-bib-95-2.07.tgz
## Current Behavior
`BioStructures.jl` fails on 2962 files, for example `d9pcya_`. Full list of files attached: 
[biostructures_test_scop95.txt](https://github.com/BioJulia/BioStructures.jl/files/2869524/biostructures_test_scop95.txt)

## Steps to Reproduce (for bugs)

 download pdbs from http://scop.berkeley.edu/downloads/pdbstyle/pdbstyle-sel-gs-bib-95-2.07.tgz and unzip
```julia
using BioStructures
read("d9pcya_.ent", PDB)
```

## Your Environment

- Package Version used: 0.4.0
- Julia Version used: 1.0.3
- Operating System and version (desktop or mobile): Linux 3.10.0-862.14.4.el7.x86_64
- Link to your project:

**Comment by jgreener64** [comment]
Fixed by https://github.com/BioJulia/BioStructures.jl/pull/12.
