### ISSUE TITLE
Error using BioStructures, no "libz1" module found

### ISSUE THREAD

**Issue by kool7d** [BioJulia/BioStructures.jl#14]
> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Current Behavior

The module "libz1" cannot be found.
## Steps to Reproduce (for bugs)

1.add BioStructures
2.using BioStructures
3.
4.

## Context

I am installing a fresh JuliaPro with julia 1.3, now I am adding packages
## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by kool7d** [comment]
Fixed by adding CodecZlib first

**Comment by kool7d** [comment]
Appears to instead be a problem with Libz

**Comment by jgreener64** [comment]
Thanks for making me aware, hopefully it will be sorted soon.
