### ISSUE TITLE
convert pdb to mol

### ISSUE THREAD

**Issue by Nick-Mul** [BioJulia/BioStructures.jl#38]
Not an issue, the package looks great but I was looking to feed a ligand into the MolecularGraph.jl package and I was wondering if you had a suggestion of how to convert a ligand.pbd into a mol/sdf in Julia?

**Comment by jgreener64** [comment]
It can't be done with BioStructures.jl but it looks like MOL2 and SDF are [supported file formats](https://chemfiles.org/chemfiles/latest/formats.html#list-of-supported-formats) in Chemfiles.jl, so you could try that.

**Comment by Nick-Mul** [comment]
Thanks Joe.
