### ISSUE TITLE
export fixlists!

### ISSUE THREAD

**Issue by shuuul** [BioJulia/BioStructures.jl#41]
I am doing structure modeling from images, so I need to manipulate the atoms and residues. Is it possible to export the `fixlists!` function, so I can update the atom_list after adding some atoms. OR are there other ways I can build a new protein structure using the current API?

**Comment by jgreener64** [comment]
There isn't much in the current API for doing this. It's on the wish list but I won't have any time soon sadly.

You can call `BioStructures.fixlists!` to access that function though. It's not exported because it requires careful use, see the internals for examples.
