### ISSUE TITLE
x, y, z seem too generic to export

### ISSUE THREAD

**Issue by timholy** [BioJulia/BioStructures.jl#49]
These conflict with variables of the same names. For example, if one wanted to plot all the atoms, one can imagine passing variables `x`, `y`, `z` to Makie. `x!`, `y!`, and `z!` are only a tiny bit better, these just seem like names that BioStructures should not claim to own.

**Comment by jgreener64** [comment]
I'm happy to not export these.

It will be a breaking change though, so if you have any other suggestions we could roll them into one release.

**Comment by timholy** [comment]
Agreed, that was the purpose of reporting without a PR. Can you put a "breaking" label on this? (I can't.)

**Comment by jgreener64** [comment]
`x`, `x!`, etc. are no longer exported.
